### Final Project for INFS580 BIG DATA,  using python pandas library and matplotlib to analyze and visualize data collected from 3 data sets; Movies, Ratings, and Users data sets

In [ ]:
# Srividya Panchagnula , INFS580 FALL 2022, DUE DATE DEC 5TH 2022 
#FINAL PROJECT USING PYTHON

In [ ]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
from matplotlib import style
import seaborn as sns
%matplotlib inline

## Read the file data

In [ ]:
movies_df = pd.read_csv(
    'movies.dat',
    sep='::',
    names=['MovieID','Title','Genres'],
    engine='python',
    header=None,
    encoding='latin-1'
)
users_df = pd.read_csv(
    'users.dat',
    sep='::',
    names=['UserID','Gender','Age', 'Occupation', 'zip-code'],
    engine='python',
    header=None
)
ratings_df = pd.read_csv(
    'ratings.dat',
    sep='::',
    names=['UserID','MovieID','Rating', 'Timestamp'],
    parse_dates=['Timestamp'],
    engine='python',
    header=None
)


printing the converted .csv files into a new directory using os library

In [ ]:
import os
os.makedirs('finalassgn', exist_ok=True)
movies_df.to_csv('finalassgn/movies.csv')
users_df.to_csv('finalassgn/users.csv')
ratings_df.to_csv('finalassgn/ratings.csv')

In [ ]:
movies_df.to_csv()

',MovieID,Title,Genres\n0,1,Toy Story (1995),Animation|Children\'s|Comedy\n1,2,Jumanji (1995),Adventure|Children\'s|Fantasy\n2,3,Grumpier Old Men (1995),Comedy|Romance\n3,4,Waiting to Exhale (1995),Comedy|Drama\n4,5,Father of the Bride Part II (1995),Comedy\n5,6,Heat (1995),Action|Crime|Thriller\n6,7,Sabrina (1995),Comedy|Romance\n7,8,Tom and Huck (1995),Adventure|Children\'s\n8,9,Sudden Death (1995),Action\n9,10,GoldenEye (1995),Action|Adventure|Thriller\n10,11,"American President, The (1995)",Comedy|Drama|Romance\n11,12,Dracula: Dead and Loving It (1995),Comedy|Horror\n12,13,Balto (1995),Animation|Children\'s\n13,14,Nixon (1995),Drama\n14,15,Cutthroat Island (1995),Action|Adventure|Romance\n15,16,Casino (1995),Drama|Thriller\n16,17,Sense and Sensibility (1995),Drama|Romance\n17,18,Four Rooms (1995),Thriller\n18,19,Ace Ventura: When Nature Calls (1995),Comedy\n19,20,Money Train (1995),Action\n20,21,Get Shorty (1995),Action|Comedy|Drama\n21,22,Copycat (1995),Crime|Drama|Thriller\n22,23,Assassins (1995),Thriller\n23,24,Powder (1995),Drama|Sci-Fi\n24,25,Leaving Las Vegas (1995),Drama|Romance\n25,26,Othello (1995),Drama\n26,27,Now and Then (1995),Drama\n27,28,Persuasion (1995),Romance\n28,29,"City of Lost Children, The (1995)",Adventure|Sci-Fi\n29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) (1995),Drama\n30,31,Dangerous Minds (1995),Drama\n31,32,Twelve Monkeys (1995),Drama|Sci-Fi\n32,33,Wings of Courage (1995),Adventure|Romance\n33,34,Babe (1995),Children\'s|Comedy|Drama\n34,35,Carrington (1995),Drama|Romance\n35,36,Dead Man Walking (1995),Drama\n36,37,Across the Sea of Time (1995),Documentary\n37,38,It Takes Two (1995),Comedy\n38,39,Clueless (1995),Comedy|Romance\n39,40,"Cry, the Beloved Country (1995)",Drama\n40,41,Richard III (1995),Drama|War\n41,42,Dead Presidents (1995),Action|Crime|Drama\n42,43,Restoration (1995),Drama\n43,44,Mortal Kombat (1995),Action|Adventure\n44,45,To Die For (1995),Comedy|Drama\n45,46,How to Make an American Quilt (1995),Drama|Romance\n46,47,Seven (Se7en) (1995),Crime|Thriller\n47,48,Pocahontas (1995),Animation|Children\'s|Musical|Romance\n48,49,When Night Is Falling (1995),Drama|Romance\n49,50,"Usual Suspects, The (1995)",Crime|Thriller\n50,51,Guardian Angel (1994),Action|Drama|Thriller\n51,52,Mighty Aphrodite (1995),Comedy\n52,53,Lamerica (1994),Drama\n53,54,"Big Green, The (1995)",Children\'s|Comedy\n54,55,Georgia (1995),Drama\n55,56,Kids of the Round Table (1995),Adventure|Children\'s|Fantasy\n56,57,Home for the Holidays (1995),Drama\n57,58,"Postino, Il (The Postman) (1994)",Drama|Romance\n58,59,"Confessional, The (Le Confessionnal) (1995)",Drama|Mystery\n59,60,"Indian in the Cupboard, The (1995)",Adventure|Children\'s|Fantasy\n60,61,Eye for an Eye (1996),Drama|Thriller\n61,62,Mr. Holland\'s Opus (1995),Drama\n62,63,Don\'t Be a Menace to South Central While Drinking Your Juice in the Hood (1996),Comedy\n63,64,Two if by Sea (1996),Comedy|Romance\n64,65,Bio-Dome (1996),Comedy\n65,66,Lawnmower Man 2: Beyond Cyberspace (1996),Sci-Fi|Thriller\n66,67,Two Bits (1995),Drama\n67,68,French Twist (Gazon maudit) (1995),Comedy|Romance\n68,69,Friday (1995),Comedy\n69,70,From Dusk Till Dawn (1996),Action|Comedy|Crime|Horror|Thriller\n70,71,Fair Game (1995),Action\n71,72,Kicking and Screaming (1995),Comedy|Drama\n72,73,"Mis√©rables, Les (1995)",Drama|Musical\n73,74,Bed of Roses (1996),Drama|Romance\n74,75,Big Bully (1996),Comedy|Drama\n75,76,Screamers (1995),Sci-Fi|Thriller\n76,77,Nico Icon (1995),Documentary\n77,78,"Crossing Guard, The (1995)",Drama\n78,79,"Juror, The (1996)",Drama|Thriller\n79,80,"White Balloon, The (Badkonake Sefid ) (1995)",Drama\n80,81,Things to Do in Denver when You\'re Dead (1995),Crime|Drama|Romance\n81,82,Antonia\'s Line (Antonia) (1995),Drama\n82,83,Once Upon a Time... When We Were Colored (1995),Drama\n83,84,Last Summer in the Hamptons (1995),Comedy|Drama\n84,85,Angels and Insects (1995),Drama|Romance\n85,86,White Squall (1996),Adventure|Drama\n86,87,Dunston Checks In (1996),Children\'s|Comedy\n87,88,Black Sheep (1996),Comedy\n88,89,Nick of Time (1995),Action|Thriller\n89,90,"Journey of August King, The (1995)",Drama\n90,92,Mary Reilly (1996),Drama|Thriller\n91,93,Vampire in Brooklyn (1995),Comedy|Romance\n92,94,Beautiful Girls (1996),Drama\n93,95,Broken Arrow (1996),Action|Thriller\n94,96,In the Bleak Midwinter (1995),Comedy\n95,97,"Hate (Haine, La) (1995)",Drama\n96,98,Shopping (1994),Action|Thriller\n97,99,Heidi Fleiss: Hollywood Madam (1995),Documentary\n98,100,City Hall (1996),Drama|Thriller\n99,101,Bottle Rocket (1996),Comedy\n100,102,Mr. Wrong (1996),Comedy\n101,103,Unforgettable (1996),Thriller\n102,104,Happy Gilmore (1996),Comedy\n103,105,"Bridges of Madison County, The (1995)",Drama|Romance\n104,106,Nobody Loves Me (Keiner liebt mich) (1994),Comedy|Drama\n105,107,Muppet Treasure Island (1996),Adventure|Children\'s|Comedy|Musical\n106,108,Catwalk (1995),Documentary\n107,109,Headless Body in Topless Bar (1995),Comedy\n108,110,Braveheart (1995),Action|Drama|War\n109,111,Taxi Driver (1976),Drama|Thriller\n110,112,Rumble in the Bronx (1995),Action|Adventure|Crime\n111,113,Before and After (1996),Drama|Mystery\n112,114,Margaret\'s Museum (1995),Drama\n113,115,Happiness Is in the Field (1995),Comedy\n114,116,Anne Frank Remembered (1995),Documentary\n115,117,"Young Poisoner\'s Handbook, The (1995)",Crime\n116,118,If Lucy Fell (1996),Comedy|Romance\n117,119,"Steal Big, Steal Little (1995)",Comedy\n118,120,Race the Sun (1996),Drama\n119,121,"Boys of St. Vincent, The (1993)",Drama\n120,122,Boomerang (1992),Comedy|Romance\n121,123,Chungking Express (1994),Drama|Mystery|Romance\n122,124,"Star Maker, The (Uomo delle stelle, L\') (1995)",Drama\n123,125,Flirting With Disaster (1996),Comedy\n124,126,"NeverEnding Story III, The (1994)",Adventure|Children\'s|Fantasy\n125,127,"Silence of the Palace, The (Saimt el Qusur) (1994)",Drama\n126,128,Jupiter\'s Wife (1994),Documentary\n127,129,Pie in the Sky (1995),Comedy|Romance\n128,130,Angela (1995),Drama\n129,131,Frankie Starlight (1995),Drama|Romance\n130,132,Jade (1995),Thriller\n131,133,Nueba Yol (1995),Comedy|Drama\n132,134,Sonic Outlaws (1995),Documentary\n133,135,Down Periscope (1996),Comedy\n134,136,From the Journals of Jean Seberg (1995),Documentary\n135,137,Man of the Year (1995),Documentary\n136,138,"Neon Bible, The (1995)",Drama\n137,139,Target (1995),Action|Drama\n138,140,Up Close and Personal (1996),Drama|Romance\n139,141,"Birdcage, The (1996)",Comedy\n140,142,Shadows (Cienie) (1988),Drama\n141,143,Gospa (1995),Drama\n142,144,"Brothers McMullen, The (1995)",Comedy\n143,145,Bad Boys (1995),Action\n144,146,"Amazing Panda Adventure, The (1995)",Adventure|Children\'s\n145,147,"Basketball Diaries, The (1995)",Drama\n146,148,"Awfully Big Adventure, An (1995)",Drama\n147,149,Amateur (1994),Crime|Drama|Thriller\n148,150,Apollo 13 (1995),Drama\n149,151,Rob Roy (1995),Drama|Romance|War\n150,152,"Addiction, The (1995)",Horror\n151,153,Batman Forever (1995),Action|Adventure|Comedy|Crime\n152,154,Belle de jour (1967),Drama\n153,155,Beyond Rangoon (1995),Drama|War\n154,156,Blue in the Face (1995),Comedy\n155,157,Canadian Bacon (1994),Comedy|War\n156,158,Casper (1995),Adventure|Children\'s\n157,159,Clockers (1995),Drama\n158,160,Congo (1995),Action|Adventure|Mystery|Sci-Fi\n159,161,Crimson Tide (1995),Drama|Thriller|War\n160,162,Crumb (1994),Documentary\n161,163,Desperado (1995),Action|Romance|Thriller\n162,164,Devil in a Blue Dress (1995),Crime|Film-Noir|Mystery|Thriller\n163,165,Die Hard: With a Vengeance (1995),Action|Thriller\n164,166,"Doom Generation, The (1995)",Comedy|Drama\n165,167,Feast of July (1995),Drama\n166,168,First Knight (1995),Action|Adventure|Drama|Romance\n167,169,Free Willy 2: The Adventure Home (1995),Adventure|Children\'s|Drama\n168,170,Hackers (1995),Action|Crime|Thriller\n169,171,Jeffrey (1995),Comedy\n170,172,Johnny Mnemonic (1995),Action|Sci-Fi|Thriller\n171,173,Judge Dredd (1995),Action|Adventure|Sci-Fi\n172,174,Jury Duty (1995),Comedy\n173,175,Kids (1995),Drama\n174,176,Living in Oblivion (1995),Comedy\n175,177,Lord of Illusions (1995),Horror\n176,178,Love & Human Remains (1993),Comedy\n177,179,Mad Love (1995),Drama|Romance\n178,180,Mallrats (1995),Comedy\n179,181,Mighty Morphin Power Rangers: The Movie (1995),Action|Children\'s\n180,182,Moonlight and Valentino (1995),Drama|Romance\n181,183,Mute Witness (1994),Thriller\n182,184,Nadja (1994),Drama\n183,185,"Net, The (1995)",Sci-Fi|Thriller\n184,186,Nine Months (1995),Comedy\n185,187,Party Girl (1995),Comedy\n186,188,"Prophecy, The (1995)",Horror\n187,189,Reckless (1995),Comedy\n188,190,Safe (1995),Thriller\n189,191,"Scarlet Letter, The (1995)",Drama\n190,192,"Show, The (1995)",Documentary\n191,193,Showgirls (1995),Drama\n192,194,Smoke (1995),Drama\n193,195,Something to Talk About (1995),Comedy|Drama|Romance\n194,196,Species (1995),Horror|Sci-Fi\n195,197,"Stars Fell on Henrietta, The (1995)",Drama\n196,198,Strange Days (1995),Action|Crime|Sci-Fi\n197,199,"Umbrellas of Cherbourg, The (Parapluies de Cherbourg, Les) (1964)",Drama|Musical\n198,200,"Tie That Binds, The (1995)",Thriller\n199,201,Three Wishes (1995),Drama\n200,202,Total Eclipse (1995),Drama|Romance\n201,203,"To Wong Foo, Thanks for Everything! Julie Newmar (1995)",Comedy\n202,204,Under Siege 2: Dark Territory (1995),Action\n203,205,Unstrung Heroes (1995),Comedy|Drama\n204,206,Unzipped (1995),Documentary\n205,207,"Walk in the Clouds, A (1995)",Drama|Romance\n206,208,Waterworld (1995),Action|Adventure\n207,209,White Man\'s Burden (1995),Drama\n208,210,Wild Bill (1995),Western\n209,211,"Browning Version, The (1994)",Drama\n210,212,Bushwhacked (1995),Comedy\n211,213,Burnt By the Sun (Utomlyonnye solntsem) (1994),Drama\n212,214,Before the Rain (Pred dozhdot) (1994),Drama\n213,215,Before Sunrise (1995),Drama|Romance\n214,216,Billy Madison (1995),Comedy\n215,217,"Babysitter, The (1995)",Drama|Thriller\n216,218,Boys on the Side (1995),Comedy|Drama\n217,219,"Cure, The (1995)",Drama\n218,220,Castle Freak (1995),Horror\n219,222,Circle of Friends (1995),Drama|Romance\n220,223,Clerks (1994),Comedy\n221,224,Don Juan DeMarco (1995),Comedy|Drama|Romance\n222,225,Disclosure (1994),Drama|Thriller\n223,226,Dream Man (1995),Thriller\n224,227,Drop Zone (1994),Action\n225,228,Destiny Turns on the Radio (1995),Comedy\n226,229,Death and the Maiden (1994),Drama|Thriller\n227,230,Dolores Claiborne (1994),Drama|Thriller\n228,231,Dumb & Dumber (1994),Comedy\n229,232,Eat Drink Man Woman (1994),Comedy|Drama\n230,233,Exotica (1994),Drama\n231,234,Exit to Eden (1994),Comedy\n232,235,Ed Wood (1994),Comedy|Drama\n233,236,French Kiss (1995),Comedy|Romance\n234,237,Forget Paris (1995),Comedy|Romance\n235,238,Far From Home: The Adventures of Yellow Dog (1995),Adventure|Children\'s\n236,239,"Goofy Movie, A (1995)",Animation|Children\'s|Comedy|Romance\n237,240,Hideaway (1995),Thriller\n238,241,Fluke (1995),Children\'s|Drama\n239,242,Farinelli: il castrato (1994),Drama|Musical\n240,243,Gordy (1995),Comedy\n241,244,Gumby: The Movie (1995),Animation|Children\'s\n242,245,"Glass Shield, The (1994)",Crime|Drama\n243,246,Hoop Dreams (1994),Documentary\n244,247,Heavenly Creatures (1994),Drama|Fantasy|Romance|Thriller\n245,248,Houseguest (1994),Comedy\n246,249,Immortal Beloved (1994),Drama|Romance\n247,250,Heavyweights (1994),Children\'s|Comedy\n248,251,"Hunted, The (1995)",Action\n249,252,I.Q. (1994),Comedy|Romance\n250,253,Interview with the Vampire (1994),Drama|Horror\n251,254,Jefferson in Paris (1995),Drama\n252,255,"Jerky Boys, The (1994)",Comedy\n253,256,Junior (1994),Comedy|Sci-Fi\n254,257,Just Cause (1995),Mystery|Thriller\n255,258,"Kid in King Arthur\'s Court, A (1995)",Adventure|Children\'s|Comedy|Fantasy|Romance\n256,259,Kiss of Death (1995),Crime|Drama|Thriller\n257,260,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Fantasy|Sci-Fi\n258,261,Little Women (1994),Drama\n259,262,"Little Princess, A (1995)",Children\'s|Drama\n260,263,Ladybird Ladybird (1994),Drama\n261,264,"Enfer, L\' (1994)",Drama\n262,265,Like Water for Chocolate (Como agua para chocolate) (1992),Drama|Romance\n263,266,Legends of the Fall (1994),Drama|Romance|War|Western\n264,267,Major Payne (1994),Comedy\n265,268,Little Odessa (1994),Drama\n266,269,My Crazy Life (Mi vida loca) (1993),Drama\n267,270,Love Affair (1994),Drama|Romance\n268,271,Losing Isaiah (1995),Drama\n269,272,"Madness of King George, The (1994)",Drama\n270,273,Mary Shelley\'s Frankenstein (1994),Drama|Horror\n271,274,Man of the House (1995),Comedy\n272,275,Mixed Nuts (1994),Comedy\n273,276,Milk Money (1994),Comedy|Romance\n274,277,Miracle on 34th Street (1994),Drama\n275,278,Miami Rhapsody (1995),Comedy\n276,279,My Family (1995),Drama\n277,280,Murder in the First (1995),Drama|Thriller\n278,281,Nobody\'s Fool (1994),Drama\n279,282,Nell (1994),Drama\n280,283,New Jersey Drive (1995),Crime|Drama\n281,284,New York Cop (1996),Action|Crime\n282,285,Beyond Bedlam (1993),Drama|Horror\n283,286,Nemesis 2: Nebula (1995),Action|Sci-Fi|Thriller\n284,287,Nina Takes a Lover (1994),Comedy|Romance\n285,288,Natural Born Killers (1994),Action|Thriller\n286,289,Only You (1994),Comedy|Romance\n287,290,Once Were Warriors (1994),Crime|Drama\n288,291,Poison Ivy II (1995),Thriller\n289,292,Outbreak (1995),Action|Drama|Thriller\n290,293,"Professional, The (a.k.a. Leon: The Professional) (1994)",Crime|Drama|Romance|Thriller\n291,294,"Perez Family, The (1995)",Comedy|Romance\n292,295,"Pyromaniac\'s Love Story, A (1995)",Comedy|Romance\n293,296,Pulp Fiction (1994),Crime|Drama\n294,297,Panther (1995),Drama\n295,298,Pushing Hands (1992),Comedy\n296,299,Priest (1994),Drama\n297,300,Quiz Show (1994),Drama\n298,301,Picture Bride (1995),Drama|Romance\n299,302,Queen Margot (La Reine Margot) (1994),Drama|Romance\n300,303,"Quick and the Dead, The (1995)",Action|Adventure|Western\n301,304,Roommates (1995),Comedy|Drama\n302,305,Ready to Wear (Pret-A-Porter) (1994),Comedy\n303,306,Three Colors: Red (1994),Drama\n304,307,Three Colors: Blue (1993),Drama\n305,308,Three Colors: White (1994),Drama\n306,309,"Red Firecracker, Green Firecracker (1994)",Drama\n307,310,Rent-a-Kid (1995),Comedy\n308,311,Relative Fear (1994),Horror|Thriller\n309,312,Stuart Saves His Family (1995),Comedy\n310,313,"Swan Princess, The (1994)",Animation|Children\'s\n311,314,"Secret of Roan Inish, The (1994)",Drama\n312,315,"Specialist, The (1994)",Action\n313,316,Stargate (1994),Action|Adventure|Sci-Fi\n314,317,"Santa Clause, The (1994)",Children\'s|Comedy|Fantasy\n315,318,"Shawshank Redemption, The (1994)",Drama\n316,319,Shallow Grave (1994),Thriller\n317,320,Suture (1993),Film-Noir|Thriller\n318,321,Strawberry and Chocolate (Fresa y chocolate) (1993),Drama\n319,322,Swimming with Sharks (1995),Comedy|Drama\n320,324,"Sum of Us, The (1994)",Comedy\n321,325,National Lampoon\'s Senior Trip (1995),Comedy\n322,326,To Live (Huozhe) (1994),Drama\n323,327,Tank Girl (1995),Action|Comedy|Musical|Sci-Fi\n324,328,Tales From the Crypt Presents: Demon Knight (1995),Horror\n325,329,Star Trek: Generations (1994),Action|Adventure|Sci-Fi\n326,330,Tales from the Hood (1995),Comedy|Horror\n327,331,Tom & Viv (1994),Drama\n328,332,Village of the Damned (1995),Horror|Sci-Fi\n329,333,Tommy Boy (1995),Comedy\n330,334,Vanya on 42nd Street (1994),Drama\n331,335,"Underneath, The (1995)",Mystery|Thriller\n332,336,"Walking Dead, The (1995)",Drama|War\n333,337,What\'s Eating Gilbert Grape (1993),Drama\n334,338,Virtuosity (1995),Sci-Fi|Thriller\n335,339,While You Were Sleeping (1995),Comedy|Romance\n336,340,"War, The (1994)",Adventure|Drama\n337,341,Double Happiness (1994),Drama\n338,342,Muriel\'s Wedding (1994),Comedy|Romance\n339,343,"Baby-Sitters Club, The (1995)",Children\'s\n340,344,Ace Ventura: Pet Detective (1994),Comedy\n341,345,"Adventures of Priscilla, Queen of the Desert, The (1994)",Comedy|Drama\n342,346,Backbeat (1993),Drama|Musical\n343,347,Bitter Moon (1992),Drama\n344,348,Bullets Over Broadway (1994),Comedy\n345,349,Clear and Present Danger (1994),Action|Adventure|Thriller\n346,350,"Client, The (1994)",Drama|Mystery|Thriller\n347,351,"Corrina, Corrina (1994)",Comedy|Drama|Romance\n348,352,Crooklyn (1994),Comedy\n349,353,"Crow, The (1994)",Action|Romance|Thriller\n350,354,Cobb (1994),Drama\n351,355,"Flintstones, The (1994)",Children\'s|Comedy\n352,356,Forrest Gump (1994),Comedy|Romance|War\n353,357,Four Weddings and a Funeral (1994),Comedy|Romance\n354,358,Higher Learning (1995),Drama\n355,359,I Like It Like That (1994),Comedy|Drama|Romance\n356,360,I Love Trouble (1994),Action|Comedy\n357,361,It Could Happen to You (1994),Drama|Romance\n358,362,"Jungle Book, The (1994)",Adventure|Children\'s|Romance\n359,363,"Wonderful, Horrible Life of Leni Riefenstahl, The (Die Macht der Bilder) (1993)",Documentary\n360,364,"Lion King, The (1994)",Animation|Children\'s|Musical\n361,365,Little Buddha (1993),Drama\n362,366,Wes Craven\'s New Nightmare (1994),Horror\n363,367,"Mask, The (1994)",Comedy|Crime|Fantasy\n364,368,Maverick (1994),Action|Comedy|Western\n365,369,Mrs. Parker and the Vicious Circle (1994),Drama\n366,370,Naked Gun 33 1/3: The Final Insult (1994),Comedy\n367,371,"Paper, The (1994)",Comedy|Drama\n368,372,Reality Bites (1994),Comedy|Drama\n369,373,Red Rock West (1992),Thriller\n370,374,Richie Rich (1994),Children\'s|Comedy\n371,375,Safe Passage (1994),Drama\n372,376,"River Wild, The (1994)",Action|Thriller\n373,377,Speed (1994),Action|Romance|Thriller\n374,378,Speechless (1994),Comedy|Romance\n375,379,Timecop (1994),Action|Sci-Fi\n376,380,True Lies (1994),Action|Adventure|Comedy|Romance\n377,381,When a Man Loves a Woman (1994),Drama\n378,382,Wolf (1994),Drama|Horror\n379,383,Wyatt Earp (1994),Western\n380,384,Bad Company (1995),Action\n381,385,"Man of No Importance, A (1994)",Drama\n382,386,S.F.W. (1994),Drama\n383,387,"Low Down Dirty Shame, A (1994)",Action|Comedy\n384,388,Boys Life (1995),Drama\n385,389,"Colonel Chabert, Le (1994)",Drama|Romance|War\n386,390,Faster Pussycat! Kill! Kill! (1965),Action|Comedy|Drama\n387,391,Jason\'s Lyric (1994),Crime|Drama\n388,392,"Secret Adventures of Tom Thumb, The (1993)",Adventure|Children\'s\n389,393,Street Fighter (1994),Action\n390,394,Coldblooded (1995),Action\n391,395,Desert Winds (1995),Drama\n392,396,Fall Time (1995),Drama\n393,397,"Fear, The (1995)",Horror\n394,398,Frank and Ollie (1995),Documentary\n395,399,Girl in the Cadillac (1995),Drama\n396,400,Homage (1995),Drama\n397,401,Mirage (1995),Action|Thriller\n398,402,Open Season (1996),Comedy\n399,403,Two Crimes (1995),Comedy|Crime|Drama\n400,404,Brother Minister: The Assassination of Malcolm X (1994),Documentary\n401,405,Highlander III: The Sorcerer (1994),Action|Sci-Fi\n402,406,Federal Hill (1994),Drama\n403,407,In the Mouth of Madness (1995),Horror|Thriller\n404,408,8 Seconds (1994),Drama\n405,409,Above the Rim (1994),Drama\n406,410,Addams Family Values (1993),Comedy\n407,411,You So Crazy (1994),Comedy\n408,412,"Age of Innocence, The (1993)",Drama\n409,413,Airheads (1994),Comedy\n410,414,"Air Up There, The (1994)",Comedy\n411,415,Another Stakeout (1993),Comedy|Thriller\n412,416,Bad Girls (1994),Western\n413,417,Barcelona (1994),Comedy|Romance\n414,418,Being Human (1993),Drama\n415,419,"Beverly Hillbillies, The (1993)",Comedy\n416,420,Beverly Hills Cop III (1994),Action|Comedy\n417,421,Black Beauty (1994),Adventure|Children\'s\n418,422,Blink (1994),Thriller\n419,423,Blown Away (1994),Action|Thriller\n420,424,Blue Chips (1994),Drama\n421,425,Blue Sky (1994),Drama|Romance\n422,426,Body Snatchers (1993),Horror|Sci-Fi|Thriller\n423,427,Boxing Helena (1993),Mystery|Romance|Thriller\n424,428,"Bronx Tale, A (1993)",Drama\n425,429,Cabin Boy (1994),Comedy\n426,430,Calendar Girl (1993),Drama\n427,431,Carlito\'s Way (1993),Crime|Drama\n428,432,City Slickers II: The Legend of Curly\'s Gold (1994),Comedy|Western\n429,433,Clean Slate (1994),Comedy\n430,434,Cliffhanger (1993),Action|Adventure|Crime\n431,435,Coneheads (1993),Comedy|Sci-Fi\n432,436,Color of Night (1994),Drama|Thriller\n433,437,Cops

In [ ]:
movies_df.head()

   MovieID                               Title                        Genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [ ]:
users_df.head()

   UserID Gender  Age  Occupation zip-code
0       1      F    1          10    48067
1       2      M   56          16    70072
2       3      M   25          15    55117
3       4      M   45           7    02460
4       5      M   25          20    55455

In [ ]:
ratings_df.head()

   UserID  MovieID  Rating  Timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

**UNIVARIATE ANALYSES**

In [ ]:
movies_df.describe()

           MovieID
count  3883.000000
mean   1986.049446
std    1146.778349
min       1.000000
25%     982.500000
50%    2010.000000
75%    2980.500000
max    3952.000000

In [ ]:
users_df.describe()

            UserID          Age   Occupation
count  6040.000000  6040.000000  6040.000000
mean   3020.500000    30.639238     8.146854
std    1743.742145    12.895962     6.329511
min       1.000000     1.000000     0.000000
25%    1510.750000    25.000000     3.000000
50%    3020.500000    25.000000     7.000000
75%    4530.250000    35.000000    14.000000
max    6040.000000    56.000000    20.000000

In [ ]:
ratings_df.describe()

             UserID       MovieID        Rating     Timestamp
count  1.000209e+06  1.000209e+06  1.000209e+06  1.000209e+06
mean   3.024512e+03  1.865540e+03  3.581564e+00  9.722437e+08
std    1.728413e+03  1.096041e+03  1.117102e+00  1.215256e+07
min    1.000000e+00  1.000000e+00  1.000000e+00  9.567039e+08
25%    1.506000e+03  1.030000e+03  3.000000e+00  9.653026e+08
50%    3.070000e+03  1.835000e+03  4.000000e+00  9.730180e+08
75%    4.476000e+03  2.770000e+03  4.000000e+00  9.752209e+08
max    6.040000e+03  3.952000e+03  5.000000e+00  1.046455e+09

In [ ]:
#CHECK PERCENTAGE OF USERS BELONGING TO A GENDER - NOMINAL DATA
Users_gender = users_df['Gender'].value_counts(normalize=True).reset_index(name='percentage')
Users_gender

  index  percentage
0     M    0.717053
1     F    0.282947

In [ ]:
#AVERAGE RATING FOR EACH MOVIE - ORDINAL DATA
avg_rating = ratings_df.groupby('MovieID')['Rating'].mean()
avg_rating.describe()

count    3706.000000
mean        3.238892
std         0.672925
min         1.000000
25%         2.822705
50%         3.331546
75%         3.740741
max         5.000000
Name: Rating, dtype: float64

In [ ]:
#COUNT OF MOVIES WITH RATING MORE THAN 4
movie_count = avg_rating[avg_rating > 4].count()
movie_count

370

In [ ]:
#MOST FREQUENT USER AGE GROUP - INTERVAL DATA
users_age = users_df['Age'].value_counts()
users_age

25    2096
35    1193
18    1103
45     550
50     496
56     380
1      222
Name: Age, dtype: int64

In [ ]:
#AVERAGE AGE OF USERS
users_df['Age'].mean()

30.639238410596025

## Merge
##### Create a new dataset [Master_Data] with
##### MovieID Title UserID Age Gender Occupation Rating

In [ ]:
movie_ratings_df = pd.merge(movies_df, ratings_df, on='MovieID')
movie_ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 88829 entries, 0 to 88828
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   MovieID    88829 non-null  int64
 1   Title      88829 non-null  object
 2   Genres     88829 non-null  object
 3   UserID     88829 non-null  int64
 4   Rating     88829 non-null  float64
 5   Timestamp  88829 non-null  object
dtypes: float64(1), int64(2), object(3)
memory usage: 4.7+ MB

In [ ]:
movie_ratings_df.head()

,MovieID,Title,Genres,UserID,Rating,Timestamp
0,1,Toy Story (1995),Animation|Children's|Comedy,1,5.0,978824268
1,1,Toy Story (1995),Animation|Children's|Comedy,6,4.0,978237008
2,1,Toy Story (1995),Animation|Children's|Comedy,8,4.0,978233496
3,1,Toy Story (1995),Animation|Children's|Comedy,9,5.0,978225952
4,1,Toy Story (1995),Animation|Children's|Comedy,10,5.0,978226474

In [ ]:
movie_ratings_users_df = pd.merge(
    movie_ratings_df,
    users_df,
    on='UserID'
)
movie_ratings_users_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 88829 entries, 0 to 88828
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MovieID     88829 non-null  int64
 1   Title       88829 non-null  object
 2   Genres      88829 non-null  object
 3   UserID      88829 non-null  int64
 4   Rating      88829 non-null  float64
 5   Timestamp   88829 non-null  object
 6   Gender      88829 non-null  object
 7   Age         88829 non-null  int64
 8   Occupation  88829 non-null  int64
 9   zip-code    88829 non-null  object
dtypes: float64(1), int64(4), object(5)
memory usage: 7.5+ MB

In [ ]:
movie_ratings_users_df.head()

,MovieID,Title,Genres,UserID,Rating,Timestamp,Gender,Age,Occupation,zip-code
0,1,Toy Story (1995),Animation|Children's|Comedy,1,5.0,978824268,F,1,10,48067
1,48,Pocahontas (1995),Animation|Children's|Musical|Romance,1,5.0,978824351,F,1,10,48067
2,150,Apollo 13 (1995),Drama,1,5.0,978301777,F,1,10,48067
3,260,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Fantasy|Sci-Fi,1,4.0,978300760,F,1,10,48067
4,527,Schindler's List (1993),Drama|War,1,5.0,978824195,F,1,10,48067

### Master_Data

In [ ]:
Master_Data = movie_ratings_users_df.drop(
    ['zip-code', 'Timestamp'],
    axis=1
)

import os
os.makedirs('finalassgn', exist_ok=True)
Master_Data.to_csv('finalassgn/Master_data.csv')

Master_Data.head()

,MovieID,Title,Genres,UserID,Rating,Gender,Age,Occupation
0,1,Toy Story (1995),Animation|Children's|Comedy,1,5.0,F,1,10
1,48,Pocahontas (1995),Animation|Children's|Musical|Romance,1,5.0,F,1,10
2,150,Apollo 13 (1995),Drama,1,5.0,F,1,10
3,260,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Fantasy|Sci-Fi,1,4.0,F,1,10
4,527,Schindler's List (1993),Drama|War,1,5.0,F,1,10

In [ ]:
Master_Data.describe(include='all')

,MovieID,Title,Genres,UserID,Rating,Gender,Age,Occupation
count,88829.000000,88829,88829,88829.000000,88829.000000,88829,88829.000000,88829.000000
unique,NaN,3230,299,NaN,NaN,2,NaN,NaN
top,NaN,American Beauty (1999),Comedy,NaN,NaN,M,NaN,NaN
freq,NaN,348,10480,NaN,NaN,68226,NaN,NaN
mean,1859.268054,NaN,NaN,300.291797,3.614349,NaN,29.106913,8.016751
std,1105.712288,NaN,NaN,167.462703,1.113639,NaN,11.536921,6.336681
min,1.000000,NaN,NaN,1.000000,1.000000,NaN,1.000000,0.000000
25%,1017.000000,NaN,NaN,162.000000,3.000000,NaN,18.000000,2.000000
50%,1792.000000,NaN,NaN,302.000000,4.000000,NaN,25.000000,7.000000
75%,2770.000000,NaN,NaN,445.000000,4.000000,NaN,35.000000,14.000000
max,3952.000000,NaN,NaN,587.000000,5.000000,NaN,56.000000,20.000000

In [ ]:
Master_Data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 88829 entries, 0 to 88828
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MovieID     88829 non-null  int64
 1   Title       88829 non-null  object
 2   Genres      88829 non-null  object
 3   UserID      88829 non-null  int64
 4   Rating      88829 non-null  float64
 5   Gender      88829 non-null  object
 6   Age         88829 non-null  int64
 7   Occupation  88829 non-null  int64
dtypes: float64(1), int64(4), object(3)
memory usage: 6.1+ MB

# Top 25 movies by viewership rating

#### Avrage rating of the movies

In [ ]:
rating_avg = movie_ratings_df.groupby('Title')['Rating'].mean()
rating_avg.head()

Title
$1,000,000 Duck (1971)           3.500000
'Night Mother (1986)             4.200000
'Til There Was You (1997)        2.857143
'burbs, The (1989)               3.000000
...And Justice for All (1979)    4.052632
Name: Rating, dtype: float64

In [ ]:
rating_avg = rating_avg.sort_values(ascending=False)
rating_avg.head()

Title
Autumn Sonata (H√∂stsonaten ) (1978)    5.0
Hearts and Minds (1996)                5.0
Idiots, The (Idioterne) (1998)         5.0
One Magic Christmas (1985)             5.0
Rain (1932)                            5.0
Name: Rating, dtype: float64

#### Number of ratings for the movies

In [ ]:
rating_count = movie_ratings_df.groupby('Title')['Rating']
rating_count = rating_count.count().sort_values(ascending=False)
rating_count[:25]

Title
American Beauty (1999)                                   348
Star Wars: Episode V - The Empire Strikes Back (1980)    298
Star Wars: Episode VI - Return of the Jedi (1983)        290
Star Wars: Episode IV - A New Hope (1977)                288
Jurassic Park (1993)                                     287
Saving Private Ryan (1998)                               259
Matrix, The (1999)                                       256
Raiders of the Lost Ark (1981)                           250
Men in Black (1997)                                      246
Gladiator (2000)                                         244
Silence of the Lambs, The (1991)                         243
Terminator 2: Judgment Day (1991)                        238
Braveheart (1995)                                        234
Sixth Sense, The (1999)                                  232
Shakespeare in Love (1998)                               228
Princess Bride, The (1987)                               228
Groundhog Day (1993)                                     221
Back to the Future (1985)                                221
Schindler's List (1993)                                  216
Shawshank Redemption, The (1994)                         213
Fargo (1996)                                             211
Mission: Impossible (1996)                               210
L.A. Confidential (1997)                                 207
E.T. the Extra-Terrestrial (1982)                        206
Forrest Gump (1994)                                      202
Name: Rating, dtype: int64

In [ ]:
rating_avg_count = pd.DataFrame(data=rating_avg)
rating_avg_count['number_of_ratings'] = pd.DataFrame(rating_count)
rating_avg_count.head()

                                     Rating  number_of_ratings
Title
Autumn Sonata (H√∂stsonaten ) (1978)     5.0                  1
Hearts and Minds (1996)                 5.0                  1
Idiots, The (Idioterne) (1998)          5.0                  3
One Magic Christmas (1985)              5.0                  1
Rain (1932)                             5.0                  2

In [ ]:
rating_avg_count.describe()

            Rating  number_of_ratings
count  3230.000000        3230.000000
mean      3.325124          27.501238
std       0.771144          37.404038
min       1.000000           1.000000
25%       2.936503           4.000000
50%       3.428571          13.000000
75%       3.918056          35.000000
max       5.000000         348.000000

### Top 25 movies by viewership
### rating excluding movies with less than 10 ratings

In [ ]:
filter_data = rating_avg_count[rating_avg_count['number_of_ratings'] > 10]
filter_data[:25]

,Rating,number_of_ratings
Title,,
Wings of Desire (Der Himmel √ºber Berlin) (1987),4.733333,15
Paths of Glory (1957),4.692308,13
Seven Samurai (The Magnificent Seven) (Shichinin no samurai) (1954),4.680851,47
Wallace & Gromit: The Best of Aardman Animation (1996),4.595238,42
Paradise Lost: The Child Murders at Robin Hood Hills (1996),4.583333,12
Schindler's List (1993),4.574074,216
"Big Sleep, The (1946)",4.571429,42
"Wrong Trousers, The (1993)",4.561798,89
It Happened One Night (1934),4.555556,36
"Shawshank Redemption, The (1994)",4.553991,213
Matewan (1987),4.545455,11
"Usual Suspects, The (1995)",4.528302,159
"Godfather, The (1972)",4.497110,173
To Kill a Mockingbird (1962),4.489130,92
"Close Shave, A (1995)",4.484848,66
"Man Who Knew Too Much, The (1956)",4.466667,15
Star Wars: Episode IV - A New Hope (1977),4.465278,288
Raiders of the Lost Ark (1981),4.464000,250
Gaslight (1944),4.461538,13
Rear Window (1954),4.455556,90
Life Is Beautiful (La Vita √® bella) (1997),4.455285,123
Manon of the Spring (Manon des sources) (1986),4.454545,11
My Man Godfrey (1936),4.454545,11
"Thin Blue Line, The (1988)",4.454545,22
"Maltese Falcon, The (1941)",4.447368,76

# Feature Engineering

### The unique genres

In [ ]:
movie_ratings_df['Genres'].value_counts().head()

Comedy            10480
Drama              9544
Comedy|Romance     3915
Comedy|Drama       3707
Drama|Romance      2671
Name: Genres, dtype: int64

In [ ]:
Genres_df = movie_ratings_df['Genres'].unique()

### Genre category with a one-hot encoding ( 1 and 0)

In [ ]:
movie_ratings_selected_df = movie_ratings_users_df[[
    'Gender',
    'Age',
    'Occupation',
    'Rating',
    'Genres'
]]

In [ ]:
Genre = movie_ratings_selected_df['Genres']
Genre = Genre.str.get_dummies().add_prefix('Genres_')
movie_ratings_genres_df = pd.concat([movie_ratings_selected_df.drop(['Genres'],axis=1 ), Genre],axis=1)
movie_ratings_genres_df = movie_ratings_genres_df.reindex(movie_ratings_selected_df.index)
movie_ratings_genres_df.head()

,Gender,Age,Occupation,Rating,Genres_Action,Genres_Adventure,Genres_Animation,Genres_Children's,Genres_Comedy,Genres_Crime,...,Genres_Fantasy,Genres_Film-Noir,Genres_Horror,Genres_Musical,Genres_Mystery,Genres_Romance,Genres_Sci-Fi,Genres_Thriller,Genres_War,Genres_Western
0,F,1,10,5.0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,F,1,10,5.0,0,0,1,1,0,0,...,0,0,0,1,0,1,0,0,0,0
2,F,1,10,5.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,F,1,10,4.0,1,1,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
4,F,1,10,5.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
movie_ratings_genres_df = pd.get_dummies(
    movie_ratings_genres_df,
    columns=['Gender']
)

In [ ]:
movie_ratings_genres_df.head()

,Age,Occupation,Rating,Genres_Action,Genres_Adventure,Genres_Animation,Genres_Children's,Genres_Comedy,Genres_Crime,Genres_Documentary,...,Genres_Horror,Genres_Musical,Genres_Mystery,Genres_Romance,Genres_Sci-Fi,Genres_Thriller,Genres_War,Genres_Western,Gender_F,Gender_M
0,1,10,5,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,10,5,0,0,1,1,0,0,0,...,0,1,0,1,0,0,0,0,1,0
2,1,10,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,10,4,1,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
4,1,10,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0

In [ ]:
movie_ratings_genres_df.columns

Index(['Age', 'Occupation', 'Rating', 'Genres_Action', 'Genres_Adventure',
       'Genres_Animation', 'Genres_Children's', 'Genres_Comedy',
       'Genres_Crime', 'Genres_Documentary', 'Genres_Drama', 'Genres_Fantasy',
       'Genres_Film-Noir', 'Genres_Horror', 'Genres_Musical', 'Genres_Mystery',
       'Genres_Romance', 'Genres_Sci-Fi', 'Genres_Thriller', 'Genres_War',
       'Genres_Western', 'Gender_F', 'Gender_M'],
      dtype='object')

### Features affecting the ratings of any particular movie.

In [ ]:
movie_ratings_genres_df.dtypes

Age                     int64
Occupation              int64
Rating                float64
Genres_Action           int64
Genres_Adventure        int64
Genres_Animation        int64
Genres_Children's       int64
Genres_Comedy           int64
Genres_Crime            int64
Genres_Documentary      int64
Genres_Drama            int64
Genres_Fantasy          int64
Genres_Film-Noir        int64
Genres_Horror           int64
Genres_Musical          int64
Genres_Mystery          int64
Genres_Romance          int64
Genres_Sci-Fi           int64
Genres_Thriller         int64
Genres_War              int64
Genres_Western          int64
Gender_F                uint8
Gender_M                uint8
dtype: object

#### Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

from sklearn import metrics

lineReg = LinearRegression(
    copy_X=True,
    fit_intercept=True,
    n_jobs=1,
    normalize=False
)

In [ ]:
movie_ratings_users_sample_df = movie_ratings_genres_df.sample(
    n=50000,
    random_state=0
)
movie_ratings_users_sample_df.head()

,Age,Occupation,Rating,Genres_Action,Genres_Adventure,Genres_Animation,Genres_Children's,Genres_Comedy,Genres_Crime,Genres_Documentary,...,Genres_Horror,Genres_Musical,Genres_Mystery,Genres_Romance,Genres_Sci-Fi,Genres_Thriller,Genres_War,Genres_Western,Gender_F,Gender_M
64180,25,20,3.0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,1
13268,25,0,2.0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1
70859,45,3,4.0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1
44036,25,2,5.0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1
29978,50,15,2.0,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
x = movie_ratings_users_sample_df.drop('Rating', axis=1)
y = movie_ratings_users_sample_df['Rating']

In [ ]:
x.shape

(50000, 22)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.20,
    random_state=0
)

In [ ]:
linear_reg = LinearRegression()

In [ ]:
linear_reg.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_pred = linear_reg.predict(x_test)

### Evaluation

In [ ]:
print(
    'y-intercept: ',
    linear_reg.intercept_
)
print(
    'Beta coefficients: ',
    linear_reg.coef_
)
print(
    'Mean Abs Error  MAE: ',
    metrics.mean_absolute_error(y_test, y_pred)
)
print(
    'Mean Sq Error  MSE: ',
    metrics.mean_squared_error(y_test, y_pred)
)
print(
    'Root Mean Sq Error RMSE:',
    np.sqrt(metrics.mean_squared_error(y_test, y_pred))
)
print(
    'r2 value: ',
    metrics.r2_score(y_test, y_pred)
)

y-intercept:  3.4446054978132232
Beta coefficients:  [ 0.00417635 -0.00290406 -0.05683106 -0.02663403  0.36776504 -0.27468965
 -0.02268764  0.0502738   0.33051552  0.24874651  0.06217411  0.41473244
 -0.26941255  0.14625133  0.01637325 -0.04751023 -0.00355147  0.02481103
  0.28429861  0.03682583  0.02463962 -0.02463962]
Mean Abs Error  MAE:  0.8993662992115887
Mean Sq Error  MSE:  1.1983237558247748
Root Mean Sq Error RMSE: 1.0946797503492858
r2 value:  0.037763005602315824

#### Age, and Occupation are the main features affecting the ratings for the movies

In [ ]:
x_train.dtypes

Age                   int64
Occupation            int64
Genres_Action         int64
Genres_Adventure      int64
Genres_Animation      int64
Genres_Children's     int64
Genres_Comedy         int64
Genres_Crime          int64
Genres_Documentary    int64
Genres_Drama          int64
Genres_Fantasy        int64
Genres_Film-Noir      int64
Genres_Horror         int64
Genres_Musical        int64
Genres_Mystery        int64
Genres_Romance        int64
Genres_Sci-Fi         int64
Genres_Thriller       int64
Genres_War            int64
Genres_Western        int64
Gender_F              uint8
Gender_M              uint8
dtype: object

In [ ]:
prediction_df = pd.DataFrame({'Test': y_test, 'Prediction': y_pred})
prediction_df.head()

       Test  Prediction
88089   5.0    3.543450
15174   4.0    3.442985
86294   4.0    3.232304
33691   5.0    3.499889
86497   4.0    3.939107